# Generated by Django 3.1.7 on 2021-04-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeavedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_source', models.ImageField(upload_to='user_images/')),
                ('image_url', models.URLField()),
                ('image_description', models.CharField(max_length=60)),
                ('image_creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('gallerys', models.ManyToManyField(to='weaver_api.Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='weaved_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaver_api.weavedimage'),
        ),
    ]
