# Generated by Django 2.2.20 on 2021-04-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeavedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_source', models.ImageField(upload_to='user_images/')),
                ('image_url', models.URLField()),
                ('image_description', models.CharField(max_length=60)),
                ('image_creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaverUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('weaved_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaved_images', to='weaver_api.WeavedImage')),
            ],
        ),
    ]
