# Generated by Django 3.1.7 on 2021-04-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weaver_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weaver_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeavedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_url', models.CharField(max_length=60)),
                ('image_description', models.CharField(max_length=60)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaver_api.gallery')),
            ],
        ),
    ]
