# Generated by Django 3.1.7 on 2021-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaver_api', '0002_gallery_weavedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='Gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='weavedimage',
            name='image_url',
            field=models.CharField(max_length=240),
        ),
    ]
