# Generated by Django 3.1.7 on 2021-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaver_api', '0003_auto_20210403_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='weavedimage',
            name='image_source',
            field=models.ImageField(default='image', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='Gallery ', max_length=50),
        ),
    ]
